"""Add coach messages table

Revision ID: 79ed88a76e66
Revises: c332c295769f
Create Date: 2026-05-25 14:53:46.259081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ed88a76e66'
down_revision: Union[str, None] = 'c332c295769f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_messages_id'), 'coach_messages', ['id'], unique=False)
    op.create_index(op.f('ix_coach_messages_user_id'), 'coach_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_messages_user_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_id'), table_name='coach_messages')
    op.drop_table('coach_messages')
    # ### end Alembic commands ###
